Blog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'patrickspeiser_at.views.home', name='home'),
    # url(r'^patrickspeiser_at/', include('patrickspeiser_at.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'Blog.blog.home', name='home'),
    url(r'^editor$', 'Blog.blog.editor', name='editor'),
    url(r'^markdown.js$', 'Blog.blog.markdown_js', name='markdown.js'),
    url(r'^add_blog_post$', 'Blog.blog.add_blog_post', name='add_blog_post'),


)

BookSearcher/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'patrickspeiser_at.views.home', name='home'),
    # url(r'^patrickspeiser_at/', include('patrickspeiser_at.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^book/(.*).json','BookSearcher.booksearcher.book_json'),
    url(r'^shelf/(.*).json','BookSearcher.booksearcher.shelf_json'),
    url(r'^shelf/(.*)','BookSearcher.booksearcher.shelf',name='shelf'),
    url(r'^search_shelf/(.*)', 'BookSearcher.booksearcher.search_shelf', name='search_shelf'),
    url(r'^$','BookSearcher.booksearcher.home',name='home'),

)

Chat/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^latest_message.json$', 'Chat.chat.latest_message_json',name='latest_message.json'),
    url(r'^messages.json', 'Chat.chat.messages_json',name='messages.json'),
    url(r'^post_message','Chat.chat.post_message',name='post_message'),
    url(r'^get_new_messages.json', 'Chat.chat.get_new_messages_json',name='get_new_messages.json'),
    url(r'^$','Chat.chat.home',name='home'),
    url(r'^clear_history','Chat.chat.clear_history',name="clear_history")



)

tweetrss/urls.py
from django.conf.urls import patterns, url
urlpatterns = patterns('',
    url(r'^$','tweetrss.tweetrss.home',name='home'),
    url(r'^(.*)','tweetrss.tweetrss.rssfeed',name='feed'),
)

urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'patrickspeiser_at.views.home', name='home'),
    # url(r'^patrickspeiser_at/', include('patrickspeiser_at.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^games','Games.games.games',name='games'),
    url(r'^$', 'Homepage.homepage.home', name='home'),
    url(r'^certificates','Homepage.homepage.certificates',name='certificates'),
    url(r'^robots.txt$','Robots.robots.robots',name='robots.txt'),
    url(r'^books/',include('BookSearcher.urls',namespace="booksearcher")),
    url(r'^tweetrss/',include('tweetrss.urls',namespace="tweetrss")),
    url(r'^blog/',include('Blog.urls',namespace="blog")),
    url(r'^chat/', include('Chat.urls',namespace="chat")),


)

Blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    date = models.DateTimeField()

BookSearcher/models.py
from django.db import models

class Shelf(models.Model):
    name = models.CharField(max_length=128,unique=True)

    @property
    def dict(self):
        books = []
        for shelved in self.shelved_set.all():
            books.append((shelved.book.title,shelved.shelved_times))
        print books[0]
        books.sort(key=lambda x:x[1],reverse=True)
        print books[0]
        return {'name':self.name,
                'books':books}

    def __str__(self):
        return self.name

class Book(models.Model):
    goodreads_id = models.IntegerField(unique=True)
    title = models.TextField()
    author = models.TextField()
    ratings_count = models.IntegerField(default=0)
    ratings_sum = models.IntegerField(default=0)
    shelves = models.ManyToManyField(Shelf,through='Shelved')

    def __str__(self):
        return self.title

    @property
    def dict(self):
        shelves = {}
        for shelved in self.shelved_set.all():
            shelves[shelved.shelf.name] = shelved.shelved_times
        return {'goodreads_id':self.goodreads_id,
                'title':self.title,
                'author':self.author,
                'ratings_count':self.ratings_count,
                'ratings_sum':self.ratings_sum,
                'shelves':shelves,
                }
    @property
    def average_rating(self):
        return float(self.ratings_sum) / max(1,self.ratings_count)

class Shelved(models.Model):
    book = models.ForeignKey(Book)
    shelf = models.ForeignKey(Shelf)
    shelved_times = models.IntegerField(default=0)

class QueuedBook(models.Model):
    goodreadsid = models.IntegerField(unique=True)

Chat/models.py
from django.db import models

class ChatMessage(models.Model):
    user = models.TextField()
    message = models.TextField()
    date = models.DateTimeField()

Games/views.py
from django.views.decorators.cache import cache_page
from django.shortcuts import render

import os

TEMPLATE_DIRS = (os.path.join(os.path.dirname(__file__), '..', 'Games', 'templates').replace('\\', '/'),)

from datetime import date, datetime

year = date.today().year
goodPlatforms = ['Win', 'X360', 'PS3']


@cache_page(60 * 60 * 6) #cache for 6 hours
def games(request):
    games = get_games_from_wikipedia()
    games.append({'date': datetime.now().strftime('%Y-%m-%d'),
                  'name': u'Today',
                  'platforms': 'Date'})
    games.sort(key=lambda x: x['date'])
    return render(request, 'games.html', {'games': games,
                                          'filter': goodPlatforms,
                                          'year': year})


#This gets the game releases from http://en.wikipedia.org/wiki/2014_in_video_gaming?printable=yes
#Ugly Code
def get_games_from_wikipedia():
    import urllib2

    opener = urllib2.build_opener()
    opener.addheaders = [('User-agent', 'Mozilla/5.0')]
    url = "http://en.wikipedia.org/wiki/%s_in_video_gaming?printable=yes" % year
    page = opener.open(url).read()
    from bs4 import BeautifulSoup

    soup = BeautifulSoup(page)
    tables = soup.find_all('table')
    #find tables
    tables = [table for table in tables
              if table.get('class')
        and 'wikitable' in table.get('class')]
    #only use the tables with release dates and platforms in them
    tables = [table for table in tables
              if 'Platform(s)' in (table.findChild('tr').text)]

    games = []
    for table in tables:
        #extract rows
        rows = table.findAll('tr')
        #remove header
        rows.pop(0)
        lastDate = -1
        for row in rows:
            elements = row.findAll('td')
            gamedate = elements[-3].text if len(elements) >= 3 else lastDate
            #assign day 32 as a placeholder
            if gamedate == '' or gamedate == 'TBA':
                gamedate = '32'
            gamedate = int(gamedate)
            if len(elements) < 2:
                continue
            name = elements[-2].text
            platforms = elements[-1].text
            game = {'date': gamedate,
                    'name': name,
                    'platforms': platforms}
            games.append(game)
            lastDate = gamedate

    #add proper dates
    import calendar

    month = 1
    last_date = 0
    for game in games:
        if game['date'] < last_date:
            month += 1
        if game['date'] == 32:
            game['date'] = calendar.monthrange(year, month)[1]
        last_date = game['date']
        game['date'] = '-'.join([str(year), str(month).rjust(2, '0'), str(game['date']).rjust(2, '0')])

    games = [game for game in games if any(goodPlatform in game['platforms'] for goodPlatform in goodPlatforms)]

    return games

Homepage/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Patrick Speiser</title>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

    <!-- Bootstrap -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

    <style>
        #content{
            padding-left:5em;
        }
    </style>

</head>

<body>

<div class="navbar navbar-default" id="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand">Patrick Speiser</div>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#about">About</a></li>
                <li><a href="#certificates">Zertifikate</a></li>
            </ul>
        </div>
    </div>
</div>

<div id='content' class="tab-content">
    <div class="tab-pane active" id="about">
        <p>

        <h2>Patrick Speiser</h2>

        <div>Student</div>
        <div>Email: <a href="mailto:mail@patrickspeiser.at">mail@patrickspeiser.at</a></div>
        <div>GitHub: <a href="https://github.com/PSpeiser/">PSpeiser</a></div>
        </p>
    </div>

    <div class="tab-pane" id="certificates">

        <h1>Udacity</h1>

        <div class="list-group">
            <a href="static/CS101.pdf" target="_blank" class="list-group-item">Introduction To Computer Science
                Building A Search Engine (CS101)</a>
            <a href="static/CS212.pdf" target="_blank" class="list-group-item">Design of Computer Programs Programming
                Principles
                (CS212)</a>
            <a href="static/CS215.pdf" target="_blank" class="list-group-item">Algorithms
                Crunching Social Networks (CS 215)</a>
            <a href="static/CS253.pdf" target="_blank" class="list-group-item">Web Application Engineering:
                How to Build a Blog (CS253)</a>
            <a href="static/CS258.pdf" target="_blank" class="list-group-item">Software Testing
                How to Make Software Fail (CS258)</a>
            <a href="static/CS262.pdf" target="_blank" class="list-group-item">Programming Languages
                Building a Web Browser (CS262)</a>
        </div>

        <h1>Coursera</h1>

        <div class="list-group">
            <a href="static/AlgoClass.pdf" target="_blank" class="list-group-item">Algorithms: Design and
                Analysis, Part I</a>
            <a href="static/Coursera interactivepython 2013.pdf" target="_blank" class="list-group-item">An Introduction
                to Interactive
                Programming in Python</a>
            <a href="static/Game Theory Class.pdf" target="_blank" class="list-group-item">Game Theory</a>
        </div>

        <h1>Various</h1>

        <div class="list-group">
            <a href="static/aiclass.pdf" target="_blank" class="list-group-item">Introduction To Artificial
                Intelligence</a>
            <a href="static/mlclass.pdf" target="_blank" class="list-group-item">Introduction to Machine Learning</a>
        </div>
    </div>
</div>
<script>
    $('#navigation a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    })

</script>
</body>
</html>

templates/blog/editor.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    {% include 'header.html' %}
    <style>
        #content {
            padding-left: 1em;

        }
        #text-input
        {
            float:left;
        }
        #preview
        {
            margin-left:1em;
            width:50em;
            float:left;
            display:inline;
        }
        #post-title
        {
            margin-left:1em;
        }
    </style>
    <script src="markdown.js">

    </script>
</head>
<body>
<form id="editor-form">
    <input type="text" id="post-title" oninput="editor.update();"></textbox>
    <div id="content">
        <textarea rows="25" cols="80" id='text-input' oninput="this.editor.update()"></textarea>
        <div id="preview" class="post">
        </div>
    </div>
   <input type="button" value="Submit" onclick="$('#editor-form').submit();">
</form>

    <script>
        $(function () { //shorthand document.ready function
        $('#editor-form').on('submit', function (e) { //use on if jQuery 1.7+
            e.preventDefault();  //prevent form from submitting
            var postdata = {'title': $("#post-title").val(),
                'text': $("#text-input").val()};
            $.post('add_blog_post', postdata);
            $("#text-input").val('Posted');
            return false;
        });
    });
          function Editor(input, preview) {
            this.update = function () {
              preview.innerHTML = "<h2>" + $("input#post-title").val() + "</h2>";
              preview.innerHTML += markdown.toHTML(input.value);
            };
            input.editor = this;
            this.update();
          }
          var getById = function (id) { return document.getElementById(id); };
          var editor = new Editor(getById("text-input"), getById("preview"));
    </script>
</body>
</html>

templates/blog/home.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title></title>
    {% include 'header.html' %}
    <style>
        #content {
            padding-left: 1em;
        }

        .post {
            border: 1px solid;
            margin: 1em;
            width: 90%;
        }
    </style>
    <script src="markdown.js">
    </script>
</head>
<body>
<div id="content">
    {% for post in posts %}
        <div class="post">
            <h2>{{ post.title }}</h2>
            <h4>{{ post.date }}</h4>

            <div class="post-text">{{ post.text }}</div>
        </div>
    {% endfor %}
</div>
<script>
    $('div.post-text').each(function (index) {
        this.innerHTML = markdown.toHTML(this.innerHTML);
    });
</script>
</body>
</html>

templates/books.html
<!DOCTYPE html>
<html>
<head>
    <title>Books</title>
    {% include 'header.html' %}
    <style>
        #content {
            margin-left: 1em;
        }
    </style>
</head>
<body>
<div id="content">
    Genre:
    {% for suggestion in suggestions %}
        <div>
            <a href="{% url 'shelf' suggestion %}?min_rating=4.0&min_shelved=10&min_ratings=1000">{{ suggestion }}</a>
        </div>
    {% endfor %}
</div>
</body>
</html>

templates/booksearcher/home.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>Books</title>
    {% include 'header.html' %}
    <style>
        #content {
            margin-left: 1em;
        }
    </style>
</head>
<body>
<div id="content">
    Genre:
    {% for suggestion in suggestions %}
        <div>
            <a href="{% url 'booksearcher:shelf' suggestion %}?min_rating=4.0&min_shelved=10&min_ratings=1000">{{ suggestion }}</a>
        </div>
    {% endfor %}
</div>
</body>
</html>

templates/booksearcher/shelf.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>{{ shelf }}</title>
    {% include 'header.html' %}
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>

    <script>
        $.extend($.fn.dataTableExt.oStdClasses, {
            "sSortAsc": "header headerSortDown",
            "sSortDesc": "header headerSortUp",
            "sSortable": "header"
        });
        $(document).ready(function () {
            $("#table").dataTable({
                "bPaginate": false,
                "bFilter": false,
                "sDom": "<'row'<'span8'l><'span8'f>r>t<'row'<'span8'i><'span8'p>>"
            });
        });</script>
    <style>
    </style>
</head>
<body>
<div><a href="{% url 'booksearcher:search_shelf' shelf %}?start_page=1&max_results=1000">Scrape Goodreads for Books</a></div>
<table id="table" class="bordered-table zebra-striped" border="3">
    <thead>
    <tr>
        <th>Name</th>
        <th>Author</th>
        <th>Average Rating</th>
        <th>Ratings</th>
        <th>Score</th>
        <th>Shelved
    </tr>
    </thead>
    {% for book in books %}
        <tr>
            <td>
                <a href="{{ book.url }}">{{ book.title }}</a>
            </td>
            <td>{{ book.author }}</td>
            <td>{{ book.average_rating }}</td>
            <td>{{ book.ratings_count }}</td>
            <td>{{ book.score }}</td>
            <td>{{ book.shelved }}</td>
        </tr>
    {% endfor %}
</table>
</body>
</html>

templates/chat/home.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>Chat</title>
    {% include 'header.html' %}
    <style>
        html, body {
            height: 100%;
        }

        #chatwindow {
            max-height:75%;
            overflow: scroll;
            width: 100%;
        }
    </style>
</head>
<body>
Chat
<div id="chatwindow"></div>
<form id="myform">
    <input type="textbox" id="username" placeholder="Username">
    <input type="textbox" id="textinput" placeholder="Message" onclick="">
    <input type="button" value="Submit" onclick="$('#myform').submit();">
    <input type="button" value="Clear History" onclick="$.post('clear_history');$('#chatwindow').empty();">
</form>
<script>
    last_id = 0
    function loadNewMessages() {
        url = 'get_new_messages.json?last_message_id=' + last_id
        $.getJSON(url, function (data) {
            $.each(data, function (i, item) {
                div = $("<div>", {
                    'id': item.id,
                    'text': item.user + ":" + item.message
                })
                if (item.id > last_id) {
                    last_id = item.id;
                }
                div.appendTo("#chatwindow");
            });
            $("#chatwindow").scrollTop($("#chatwindow")[0].scrollHeight);
            loadNewMessages();
        });
    }


    $(document).ready(function () {
        $('#textinput').keydown(function (event) {
            if (event.keyCode == 13) {
                $('#myform').submit();
                return false;
            }
        });
    });
    $(function () { //shorthand document.ready function
        $('#myform').on('submit', function (e) { //use on if jQuery 1.7+
            e.preventDefault();  //prevent form from submitting
            var postdata = {'user': $("#username").val(),
                'message': $("#textinput").val()};
            $.post('post_message', postdata);
            $("#textinput").val('');
            return false;
        });
    });
    loadNewMessages();
</script>
</body>
</html>

templates/games.html
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, user-scalable=no">
<html>
<head>
    <title>Games</title>
    {% include 'header.html' %}
    <style>
        .center {
            text-align: center;
        }
        .date
        {
            min-width:6em;
        }
    </style>
    <script>window.onload = function () {
        el = document.getElementById("target");
        window.scrollTo(window, el.offsetTop);
    }</script>
</head>
</head>
<body>

<h1>Games in {{ year }}</h1>
<h2>Filter: {{ filter }}</h2>
<table border="3">
    <tr>
        <td>Date</td>
        <td>Name</td>
        <td>Platforms</td>
    </tr>
    {% for game in games %}
        {% if game.name == 'Today' %}
            <tr>
                <td>
                    <strong>{{ game.date }}</strong>
                </td>
                <td class="center" id="target"><strong>Today</strong></td>
            </tr>
        {% else %}
            <tr>
                <td class="date">{{ game.date }}</td>
                <td>{{ game.name }}</td>
                <td>{{ game.platforms }}</td>
            </tr>
        {% endif %}
    {% endfor %}
</table>
</body>
</html>

templates/header.html
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<!-- Bootstrap -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

<style>
    body { padding-top: 70px; }
</style>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Patrick Speiser</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'blog:home' %}">Blog</a></li>
                <li><a href="{% url 'certificates' %}">Zertifikate</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projekte <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'games' %}">Spiele Release Liste</a></li>
                        <li><a href="{% url 'booksearcher:home' %}">Buchempfehler</a></li>
                        <li><a href="{% url 'tweetrss:home' %}">TweetRSS</a></li>
                        <li><a href="{% url 'chat:home' %}">Chat</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

templates/homepage/certificates.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title></title>
    {% include 'header.html' %}
    <style>
        #content {
            margin-left: 1em;
        }
    </style>
</head>
<body>

<div id="content" class="container-fluid">
    <h1>Udacity</h1>
    <div class="list-group" id="side-menu-collapse">
        <li class="list-group-item">
            <a href="static/pdf/CS101.pdf" target="_blank">Introduction To Computer Science
                Building A Search Engine (CS101)</a>
        </li>
        <li class="list-group-item">
            <a href="static/pdf/CS212.pdf" target="_blank">Design of Computer Programs Programming Principles (CS212)
            </a>
        </li>

        <li class="list-group-item">
            <a href="static/pdf/CS215.pdf" target="_blank">Algorithms
                Crunching Social Networks (CS 215)</a>
        </li>

        <li class="list-group-item">
            <a href="static/pdf/CS253.pdf" target="_blank">Web Application Engineering:
                How to Build a Blog (CS253)</a>
        </li>

        <li class="list-group-item">
            <a href="static/pdf/CS258.pdf" target="_blank">Software Testing
                How to Make Software Fail (CS258)</a>
        </li>

        <li class="list-group-item">
            <a href="static/pdf/CS262.pdf" target="_blank">Programming Languages
                Building a Web Browser (CS262)</a>
        </li>
    </div>

    <h1>Coursera</h1>

    <div class="list-group">
        <li class="list-group-item">
        <a href="static/pdf/AlgoClass.pdf" target="_blank">Algorithms: Design and
            Analysis, Part I</a>
        </li>
            <li class="list-group-item">
        <a href="static/pdf/Coursera interactivepython 2013.pdf" target="_blank">An
            Introduction
            to Interactive
            Programming in Python</a>
                </li>
        <li class="list-group-item">
        <a href="static/pdf/Game Theory Class.pdf" target="_blank">Game Theory</a>
        </li>
    </div>

    <h1>Various</h1>

    <div class="list-group">
        <li class="list-group-item">
        <a href="static/pdf/aiclass.pdf" target="_blank">Introduction To Artificial
            Intelligence</a>
        </li>
            <li class="list-group-item">
        <a href="static/pdf/mlclass.pdf" target="_blank">Introduction to Machine
            Learning</a>
        </li>
    </div>
</div>
</body>
</html>

templates/homepage/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="Description" content="Patrick Speiser, Student">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Patrick Speiser</title>

    {% include 'header.html' %}
    <style>
    #content{
        margin-left:1em;
    }
    </style>

</head>

<body>


<div id="content">
    <h2>Patrick Speiser</h2>

    <div>Student</div>
    <div>Email: <a href="mailto:mail@patrickspeiser.at">mail@patrickspeiser.at</a></div>
    <div>GitHub: <a href="https://github.com/PSpeiser/">PSpeiser</a></div>
    <div>Twitter: <a href="https://twitter.com/Doskir">Doskir</a></div>
</div>
</body>
</html>

templates/shelf.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ shelf }}</title>
    {% include 'header.html' %}
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/jquery.dataTables.min.js"></script>

    <script>
        $.extend($.fn.dataTableExt.oStdClasses, {
            "sSortAsc": "header headerSortDown",
            "sSortDesc": "header headerSortUp",
            "sSortable": "header"
        });
        $(document).ready(function () {
            $("#table").dataTable({
                "bPaginate": false,
                "bFilter": false,
                "sDom": "<'row'<'span8'l><'span8'f>r>t<'row'<'span8'i><'span8'p>>"
            });
        });</script>
    <style>
    </style>
</head>
<body>
<div><a href="{% url 'search_shelf' shelf %}?start_page=1&max_results=1000">Scrape Goodreads for Books</a></div>
<table id="table" class="bordered-table zebra-striped" border="3">
    <thead>
    <tr>
        <th>Name</th>
        <th>Author</th>
        <th>Average Rating</th>
        <th>Ratings</th>
        <th>Score</th>
        <th>Shelved
    </tr>
    </thead>
    {% for book in books %}
        <tr>
            <td>
                <a href="{{ book.url }}">{{ book.title }}</a>
            </td>
            <td>{{ book.author }}</td>
            <td>{{ book.average_rating }}</td>
            <td>{{ book.ratings_count }}</td>
            <td>{{ book.score }}</td>
            <td>{{ book.shelved }}</td>
        </tr>
    {% endfor %}
</table>
</body>
</html>

templates/tweetrss/tweetrss.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>TweetRSS</title>
    {% include 'header.html' %}
    <style>
        #content {
            margin-left: 1em;
        }
    </style>
</head>
<body>
<div id="content">
    Enter a Twitter Username and get his Tweets as an RSS Feed
    <form name="input" onsubmit="window.location = document.getElementById('username').value;return false;">
        Username: <input type="text" id="username">
        <input type="submit" value="Get RSS Feed">
    </form>
</div>
</body>
</html>